apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-perf
  name: http-perf-{{.Replica}}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-{{.Replica}}
  type: {{.serviceType}}
