apiVersion: v1
kind: Pod
metadata:
  labels:
    run: http-perf
    app: nginx-{{.Replica}}
  name: http-perf-{{.Replica}}
spec:
  nodeSelector: {{.nodeSelector}}
  containers:
  - image: quay.io/piyushgupta1551/nginx:latest
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
